# Generated by Django 3.1.1 on 2020-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.IntegerField(default=0)),
                ('studentid', models.IntegerField(default=0)),
                ('addflag', models.IntegerField(default=0)),
            ],
        ),
    ]
