# Generated by Django 3.1.1 on 2022-01-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='batch_end',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='batch_start',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
