# Generated by Django 3.1.1 on 2022-01-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0002_auto_20220113_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fcmdata',
        ),
    ]
