# Generated by Django 3.1.1 on 2022-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0004_fcmdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='altemail',
            field=models.CharField(max_length=51, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='batch_end',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='batch_start',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
