# Generated by Django 3.1.1 on 2022-01-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0006_auto_20220114_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='usertype',
            field=models.IntegerField(default=5),
        ),
    ]
