# Generated by Django 3.1.1 on 2022-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0007_userid_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='reg_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
