# Generated by Django 3.1.1 on 2021-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0007_auto_20210204_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='religion',
            field=models.CharField(max_length=50),
        ),
    ]
