# Generated by Django 3.1.1 on 2021-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0009_auto_20210204_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='father_mobile',
            field=models.IntegerField(max_length=11),
        ),
    ]
