# Generated by Django 3.1.1 on 2021-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0010_auto_20210204_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='father_mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_mobile',
            field=models.CharField(max_length=11),
        ),
    ]
