# Generated by Django 3.1.1 on 2021-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0011_auto_20210204_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='cutoff',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
