# Generated by Django 3.1.1 on 2021-02-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mectworkplace', '0014_auto_20210204_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certificate',
            new_name='certificate_details',
        ),
    ]
