from django.urls import path
from . import views



urlpatterns = [



    #path('',views.index, name='index'),
    path('check',views.check,name='check'),
    path('',views.download, name=''),
    path('index1',views.index1,name='index1'),
    path('signup',views.signup, name='signup'),
    path('signup1',views.signup1, name='signup1'),
    path('signup2',views.signup2, name='signup2'),
    path('editprofdp',views.editprofdp, name='editprofdp'),
    path('accountcreated',views.accountcreated, name='accountcreated'),
    path('notifications',views.notifications, name='notifications'),
    path('home',views.home, name='home'),
    path('search',views.search, name='search'),
    path('post',views.post, name='post'),
    path('tag',views.tag, name='tag'),
    path('comments',views.comments, name='comments'),
    path('view_members',views.view_members, name='view_members'),
    path('settings',views.settings, name='settings'),
    path('settings1',views.settings1, name='settings1'),
    path('create_group',views.create_group, name='create_group'),
    path('groups',views.groups, name='groups'),
    path('groups_more',views.more,name='groups_more'),
    path('cpass',views.cpass, name='cpass'),
    path('initial_data',views.initial_data,name='initial_data'),
    path('t2',views.t2,name='t2'),
    path('t3',views.t3,name='t3'),
    path('t4',views.t4,name='t4'),
    path('authenticate',views.authenticate,name='authenticate'),
    path('t6',views.t6,name='t6'),
    path('search-list',views.search_list,name='search-list'),
    path('t8',views.t8,name='t8'),
    path('t9',views.t9,name='t9'),
    path('pre_post',views.pre_post,name='pre_post'),
    path('add-post',views.add_post_data,name='add-post'),
    path('post_member_list',views.post_member_list,name='post_member_list'),
    path('privatepost_save',views.privatepost_save,name='privatepost_save'),
    path('t14',views.t14,name='t14'),
    path('t15',views.t15,name='t15'),
    path('home-content',views.home_content,name='home-content'),
    path('home-lazy-content',views.home_lazy_content,name='home-lazy-content'),
    path('like-save',views.like_save,name='like-save'),
    path('t19',views.t19,name='t19'),
    path('privatereply_save',views.privatereply_save,name='privatereply_save'),
    path('comment-save',views.comment_save,name='comment-save'),
    path('t22',views.t22,name='t22'),
    path('t23',views.t23,name='t23'),
    path('group-post-filter',views.group_post_filter,name='group-post-filter'),
    path('iterate-group-post-filter',views.iterate_group_post_filter,name='iterate-group-post-filter'),
    path('groupdetails',views.groupdetails,name='groupdetails'),
    path('t27',views.t27,name='t27'),
    path('t28',views.t28,name='t28'),
    path('t29',views.t29,name='t29'),
    path('t30',views.t30,name='t30'),
    path('t31',views.t31,name='t31'),
    path('userdetails',views.userdetails,name='userdetails'),
    path('t33',views.t33,name='t33'),
    path('init-notification',views.init_notification,name='init-notification'),
    path('t35',views.t35,name='t35'),
    path('notification_content',views.notification_content,name='notification_content'),
    path('t40',views.t40,name='t40'),
    path('post-delete',views.post_delete,name='post-delete'),
    path('changepassword',views.changepassword,name='changepassword'),
    path('password-save',views.password_save,name='password-save'),
    path('tutor-save',views.tutor_save,name='tutor-save'),
    path('add_tutor',views.add_tutor,name='add_tutor'),
    path('wardinfo',views.wardinfo,name='wardinfo'),
    path('t46',views.t46,name='t46'),
    path('tutor_member_list',views.tutor_member_list,name='tutor_member_list'),
    path('privatepost_save_ward',views.privatepost_save_ward,name='privatepost_save_ward'),
    path('t49',views.t49,name='t49'),
    path('t50',views.t50,name='t50'),
    path('tutor',views.tutor,name='tutor'),
    path('info',views.info,name='info'),
    path('about',views.about,name='about'),
    path('edit',views.edit,name='edit'),
    path('up',views.up,name='up'),
    path('target',views.target,name='target'),
    path('target1',views.target1,name='target1'),
    path('search/user/<int:uid>',views.prof,name='search/user'),
    path('search/group/<int:gid>',views.grp,name='search/group'),
    path('notifications/like/<int:did>',views.lc,name='notifications/like'),
    path('notifications/comment/<int:did>',views.lc,name='notification/comment'),
    path('notifications/reply/<int:did>',views.rep,name='notification/reply'),
    path('data',views.data,name='data'),
    path('certificate',views.certificate,name='certificate'),
    path('loadcomment',views.loadcomment,name='loadcomment'),
    path('loadtut',views.loadtut,name='loadtut'),
    path('namelist',views.namelist,name='namelist'),
    path('notify',views.notify,name='notify'),
    path('logout',views.logout,name='logout'),
    path('init-app',views.init_app,name='init-app'),
    path('profileinfo',views.profiledetails,name='profileinfo'),
    path('editprofdetails',views.editprofdetails,name='editprofdetails'),
    path('get-single-post',views.get_single_post,name='get-single-post'),
    #path('e',views.e,name='e'),
    #path('ply',views.ply,name='ply'),


]
